#+TITLE: Unity Shader And Effect Cookbook
#+OPTIONS: ^:{}
#+OPTIONS: \n:t 
#+HTML_HEAD: <link rel="stylesheet" href="http://orgmode.org/org-manual.css" type="text/css" />

* Basic 
** Properties
Properties {
		_MyFloatValue("This is a Float", Float) = 1.5
		_MyRangeValue("This is a Range", Range(0,10)) = 2.5
		_MyColorValue("This is a ColorAmbient Color", Color) = (0.5,1,1,1)
		_MyVectorValue("This is a Vector", Vector) = (1,2,3,4)
		_My2DValue("This is a Texture 2D", 2D) = "white" {}
		_MyRectValue("This is a Texture Rect", Rect) = "white" {}
		_MyCubeValue("This is a Texture Cube", Cube) = "white" {}
}
** SurfaceOutput
struct SurfaceOutput {  
    half3 Albedo;      //The color of the pixel  片段的颜色
    half3 Normal;      //The normal of the pixel  法线
    half3 Emission;    //The emissive color of the pixel 发出的颜色 
    half Specular;     //Specular power of the pixel    镜面高光系数
    half Gloss;        //Gloss intensity of the pixel  光泽强度
    half Alpha;        //Alpha value for the pixel     片段的透明度
};  
** Input
| 名称                      | 类型   | 意义                                                            |
|---------------------------+--------+-----------------------------------------------------------------|
| uv_XXX                    | float2 | 存放贴图的 uv 坐标                                              |
| viewDir                   | float3 | 存放视觉方向（也就是眼睛方向，摄像机方向）                      |
| COLOR                     | float4 | 存放插值后的顶点颜色                                            |
| screenPos                 | float4 | 存放屏幕空间的坐标                                              |
| worldPos                  | float3 | 存放世界坐标                                                    |
| worldRefl                 | float3 | 存放世界空间中的反射向量                                        |
| worldNormal               | float3 | 如果 surface shader 没有修改 o.Normal 则存放世界空间的法向量   |
| worldRefl;INTERNAL_DATA   | float3 | 如果 surface shader 修改了 o.Normal，则存放世界空间的反射向量。 |
| worldNormal;INTERNAL_DATA | float3 | 如果 surface shader 修改了 o.Normal，则存放世界空间的法向量。   |
*** Tips:
使用 worldRefl;INTERNAL_DATA 时， 通过 WorldReflectionVector (IN, o.Normal)来从法线贴图获得反射向量
使用 worldNormal;INTERNAL_DATA 时，通过 WorldNormalVector（IN, o.Normal）来从法线贴图获得法线
http://docs.unity3d.com/Manual/SL-SurfaceShaders.html

* Tips:
** unity 坐标系
unity 为左手坐标系。
** Shader
** Error  
*** Shader error in Too many texture interpolators would be used for ForwardBase pass (11 out of max 10)
将 #pragma target 3.0 变为 #pragma target 4.0 可解决问题
*** 如果发现颜色部分正确部分不正确
**** 检查 Input 中 viewDir lightDir 是否使用的是 float3.
使用 float 会造成 yz 分量的缺失，导致 yz 分量不为 0 时，显示错误。


** Normal Map
Normal Map 又叫 Ramp Map，其实就是法线贴图。
*** 参考资料
[[http://www.songho.ca/opengl/gl_normaltransform.html][Normal 变换矩阵推导]]
[[http://blog.csdn.net/candycat1992/article/details/41605257][Unity 中的 Normal Map]]
[[http://http.developer.nvidia.com/CgTutorial/cg_tutorial_chapter08.html][Cg 中的 Normal Map]]
[[http://learnopengl.com/#!Advanced-Lighting/Normal-Mapping][Normal Map Detail]]
