
#+TITLE: Unity Note
#+OPTIONS: ^:{}
#+OPTIONS: \n:t 
#+HTML_HEAD: <link rel="stylesheet" href="http://orgmode.org/org-manual.css" type="text/css" />
Tips: 下载 htlm 格式文件直接在浏览器中打开，可以查看格式优化过的文档。
* UI
** Canvas
Canvas 是一个区域，所有的 UI 元素必须在其中。Canvas 是包含一个 Canvas 组件的 GameObject。所有的 UI 元素必须是这个 Canvas 的子节点。
*** 元素的渲染次序
UI 元素在 Canvas 中的渲染次序，和他们在 Hierarchy 中的次序一致。第一个子节点先渲染，第二个子节点次之，等等。当两个 UI 元素重叠时，后面渲染的 UI 元素将出现在前面渲染的 UI 元素上面。通过改变 UI 元素在 Hierarchy 视图中的位置来改变他们的渲染顺序。
*** 渲染模式
ScreenSpace-Overlay 渲染模式将被渲染的 UI 元素放在场景最上面的屏幕上。如果屏幕尺寸或分辨率改变，Canvas 将会自动改尺寸来适配屏幕。
ScreenSpace-Camera 渲染模式和 ScreenSpace-Overlay 渲染模式类似，但是 Canvas 被放置在一个特定的摄像机前的指定距离处。UI 元素被该摄像机渲染，也就是说摄像机的设置会影响 UI 的显示效果。如果摄像机被设置为透视投影，透视的扭曲量可通过 Camera 的 Field Of View 来控制。
WorldSpace 渲染模式下，Canvas 就像任何场景中的物体一样。Canvas 的大小可以被手动设置，UI 元素会被基于他们的 3D 位置而绘制。
*** 实例说明
UI/Scenes/UICanvas 中，改变屏幕大小，ScreenSpace-Overlay 和 ScreenSpace-Camera 模式下的文字大小不会改变，Canvas 的尺寸会随着屏幕大小而调整。WorldSpace 模式下的文字大小会改变，Canvas 的尺寸不会随屏幕大小而改变。
** Basic Layout
*** Rect Transform
Rect Transform 是专门针对 UI 开发的用来代替 Transform 的。Rect Transform 比 Transform 要多 width 和 height 两个属性，来指定一个矩形区域。
对于包含 RectTransform 属性的游戏对象，Rect Tool 在改变尺寸时，会改变 RectTransform 的 size 大小。对于不包含 RectTransform 属性的游戏对象（如 Sprite），Rect Tool 改变的是游戏对象的 Scale。
**** Pivot
中心点会影响缩放、旋转、改变尺寸的结果。
**** Anchors
如果 Rect Transform 的父节点也是个 RectTransform，那么子节点可以通过多种方式 anchored 到父节点上。(其实，Anchors 定义了一个相对于父节点矩形的 Anchor 矩形区域-AnchorRect。)
**** PosX PosY Width Height
当 Anchors 重合时，PosX PosY 表示 Pivot 相对于 Anchors 的位置,Width Height 表示矩形区域的宽高。
当 Anchors 在水平方向上重合，在竖直方向上分开时，PosX 表示 Pivot 相对于 Anchors 的水平位置，Width 表示矩形区域的宽。PosY 变为了 Top，表示中心点相对于 Anchors 最上面的距离，Height 变为了 Bottom 表示中心点相对于 Anchors 最下面的距离。
当 Anchors 全部分开后，属性变为了 Left Right Top Bottom，分别表示节点的 Rect 相对于 AnchorRect 的位置。
**** Blue 模式和 Raw 编辑模式
Blue 模式下，会忽略 UI 元素的 Local Rotation 和 Local Scale，方便以原來的旋转和大小调整物体。
Raw 模式下，调整 Pivot 和 Anchors 时会保持 UI 元素的位置和大小。
**** Script 中常用属性和方法
***** rectTransform.rect
rectTransform.rect 该属性返回表示当前 UI 元素的矩形区域，position 表示矩形左下的坐标（基于当前 UI 元素的本地坐标），size 表示矩形区域的尺寸。
***** rectTransform.TransformPoint
rectTransform.TransformPoint(pos)可以将 UI 元素的本地坐标转换为世界坐标。
***** rectTransform 属性设置
在脚本中设置 rectTransform 属性时，先将 rectTransform 所属的 GameObject 加到场景中，然后再设置 rectTransform 相关的属性，否则 GameObject 在加入场景时会修改 RectTransform 的属性。
#+BEGIN_SRC c#
// 下面代码可以将一个 RectTransform 设置为其父节点大小，中心和其父节点重合
public static void ResetRectToFullScreenAndInMiddle (RectTransform rectTransform)
{
  if (rectTransform != null) {
    rectTransform.pivot = new Vector2 (0.5f, 0.5f);
    rectTransform.localScale = Vector3.one;
    rectTransform.anchorMin = Vector2.zero;
    rectTransform.anchorMax = Vector2.one;
    rectTransform.sizeDelta = Vector2.zero;
    rectTransform.localPosition = Vector3.zero;
  }
}
#+END_SRC

** Visual Components
*** Text
Best Fit 选项会修改文字的尺寸来适应可显示的区域。
*** Image
ImageType 选项定义了被应用的 Sprite 如何显示:
Simple 表示均等地缩放整个 sprite;
Sliced 表示使用 3x3 分割的 Sprite，当修改尺寸时，四个角不会扭曲变形，只有中间的部分会缩放;
Tiled 和 Sliced 类似，但是它不会缩放中心的内容，它是重复中心的内容;
Filled 和 Simple 一样的方式显示 Sprite，只是它会从原点开始以指定的方向、方法以及总量来显示图片。
选择 Simple 或 Filled 时，可以通过 Set Native Size 将 Image 的大小设置为原始图片的大小。
*** Mask
Mask 组件不是一个可视化的 UI 控件，但它是控制子 UI 元素显示的一种方式。Mask 会限制子 UI 元素的形状为他们父节点的形状。
*** Effect
Outline 组件可以为 UI 元素添加描边效果。通过修改 EffectColor 为描边设置颜色，EffectDistance 设置描边的相对位置。
** Interaction Components
*** Selectable Base Class
Selectable 是所有可交互组件的基类，它按照统一的方式来处理元素。
| Property     | Function                                                                                                   |
|--------------+------------------------------------------------------------------------------------------------------------|
| Interactible | 该属性决定了组件是否接受输入。当它被设置为 false 时，交互是不可用的，而且转换状态被设置为 Disable          |
| Transition   | 对于一个可选中的组件，依据它当前所在状态有很多转换选项。不同的状态包括：normal，highlight,pressed,disabled |
| Navigation   | 有一系列的导航选项来控制如何实现键盘导航                                                                   |
*** Button
状态改变触发的 UnityEvent：OnClick
*** Toggle
将多个 Toggle 的 Group 属性指定相同的包含 ToggleGroup 组件的 GameObject，可将这些 Toggle 指定为一组。
状态改变触发的 UnityEvent：OnValueChanged
*** Toggle Group
为 GameObject 添加 ToggleGroup 可以分组管理 Toggle。Allow Switch Off 属性表示，点击分组中 On 的 Toggle，该 Toggle 会变为 Off。
*** Slider
Slider 有一个整型值，拖拉可以在最小和最大范围内改变该值。WholeNumbers 属性可以指定整型值为整数。
状态改变触发的 UnityEvent：OnValueChanged
*** ScrollBar
ScrollBar 有一个 0 到 1 的整型值。Number Of Steps 属性表示拖动 ScrollBar 从 0 变为 1 一共需要多少个 Step，该值为 0 时，ScrollBar 的拖动是平滑的。
状态改变触发的 UnityEvent：OnValueChanged
*** Dropdown
状态改变触发的 UnityEvent：OnValueChanged
*** InputField
ContentType 属性表示输入框内容的类型。Standard、Autocorrected、Integer Number、Decimal Number、Alphanumeric、Name、Email、Password*、Pin、Custom。
OnValueChanged： 输入框中内容改变会触发该 UnityEvent
EndEdit： 编辑完成时会触发该 UnityEvent
*** ScrollRect(ScrollView)
Horizontal 选项控制是否可以在水平方向滑动。
Vertical 选项控制是否可以在竖直方向滑动
MovementType 选项控制移动的类型，Unrestricted 表示不限制滑动范围；Clamped 表示限制滑动范围；Elastic 表示限制滑动范围，并且滑出范围后会自动回弹回来。
ScrollRect 下的子节点 Viewport 用来控制显示区域，Viewport 上有一个 Mask 组件。Viewport 下的子节点 Content 用来放置滑动区域内要显示的内容。
Vertical/Horizontal ScrollBar 属性用来绑定 ScrollRect 和 ScrollBar。
OnValueChanged：滑动位置改变后触发该 UnityEvent
** Animation Integration
点击控件属性面板中的 Auto Generate Animation 按钮，可以为该控件生成相关动画配置。
选中 Animation 对象，在 Inspector 面板中有 LoopTime 选项可以控制是否循环播放动画。
Tips:
UI 的 Animation 变换模式和 Unity 遗弃的动画系统是不兼容的。只能使用 Animator 组件。
** Auto Layout
自动布局系统提供了很多方式将元素放置在嵌套的布局分组中，例如 horizontal groups,vertical groups,grids。它允许元素依据其包含的内容自动地改变大小。自动布局系统是以 RectTransform 为基础构建的。
*** Layout Element
自动布局系统是基于布局元素和布局控制器的。一个布局元素是包含 RectTransform 组件的一个游戏对象，当然这个游戏对象可以包含其他任何组件。布局元素知道它自己的大小。布局元素不会直接设置自己的大小，但是其他的就像布局控制功能的组件可以利用布局元素提供的信息来计算出一个尺寸大小让其使用。
一个布局元素定义了下面的属性：Minimum width、Minimum height、Preferred width、Preferred height、Flexible width、Flexible height。

Layout Controller 使用 Layout elements 提供的信息的例子是 Content Size Fitter 和各种 Layout Group 组件。修改 layout group 中 layout elements 尺寸遵从下面原则：首先会分配最小的尺寸；如果还有足够的空间，就分配 PreferredSize;如果还有额外的空间可用，就分配 flexible size。

任何包含 RectTransform 的游戏对象都可以被当做一个布局元素。它们的默认 mininum、prefered、和 flexible 尺寸为 0.特定的组件加到该游戏对象上时会改变这些布局属性的值。例如，Image 和 Text 组件会修改 preferred width 和 height 来匹配 sprite 和 text 的内容。

如果你想覆盖一个游戏对象的布局属性（minimum, preferred, or flexible size),你可以为该游戏对象添加一个 Layout Element 组件。
*** Layout Controller
Layout Controller 组件可以用来控制一个过多个 Layout Element 的尺寸和位置。一个 Layout Controller 可以控制它自己所在的 GameObject 的 Layout Element 也可以控制子节点的 Layout Element。
一个功能为 LayoutController 的组件其功能同时可以为 Layout Element.
**** Content Size Fitter
Content Size Fitter 的功能是控制它自己所在 GameObject 的 LayoutElement。如果将 Horizontal Fit 或 Vertical Fit 设置为 Preferred, Rect Transform 将会调整它自己的 width and/or height 来适应内容的大小.
**** Aspect Ratio Fitter
Aspect Ratio Fitter 的功能是控制它自己所在 GameObject 的 LayoutElement 的 Size。
Aspect Mode 选项控制如何改变矩形尺寸来满足特定纵横比。
| 属性                  | 功能                                                                                                                                  |
|-----------------------+---------------------------------------------------------------------------------------------------------------------------------------|
| None                  | 矩形不必符合指定宽高比                                                                                                                |
| Width Controls Height | 高度基于宽度来自动调整                                                                                                                |
| Height Controls Width | 宽度基于高度自动调整                                                                                                                  |
| Fit In Parent	       | 宽度、高度、位置、锚点自动基于父节点调整， 使矩形在父节点内并且保持指定宽高比，这会让有些在父节点内的空间没有被当前节点的矩形所覆盖。 |
| Envelope Parent       | 宽度、高度、位置、锚点自动基于父节点调整，使矩形覆盖父节点的整个区域且保持特定宽高比，这会让当前节点的矩形超出父节点的范围。          |
Aspect Ratio 选项用来设置 width/height 的比值。
**** Layout Groups
作为 layout controller 的 layout group，它的作用是控制子 layout elements 的位置和尺寸。
一个 layout group 不会控制自己的尺寸。它作为一个 layout element 可以被其他 layout controller 控制或者是手动设置。
无论一个 layout group 分配了多大尺寸，它都会尽力为每一个子 layout element 分配合适的空间。layout group 可以以任意的方式嵌套。
**** Driven Rect Transform properties
因为自动布局系统中的 layout controller 会自动控制某些 UI 元素的尺寸和位置，所以不要手动编辑他们的尺寸和位置，否则，这些改变会被 layout controller 的自动布局重置。
Rect Transform 有一个属性驱动的概念来达到上面的目的。例如，ContentSizeFitter 有 HorizontalFit 属性来设置使用 Minimum 还是 Preferred 来控制 GameObject 的 RectTransform 的宽度，选择其中一个就会让 Rect Transform 的 width 属性变为只读。
属性驱动还可以防止手动的编辑。一个布局可以只随 GameView 的分辨率或尺寸而变化。这改变驱动属性的值，反过来又会修改 layout element 的位置和尺寸。但是，只改变 GameView 的大小不应该将 Scene 标记为未保存的。为了避免这样，驱动值不会作为 Scene 的部分被保存，驱动值的改动不会标记场景是否修改。
*** Technical Details
自动布局系统来自内置的某些组件，但是也可以创建新的组件来实现自定义的布局控制。可以通过实现自动布局系统可识别的特定接口来创建这样的组件。
**** Layout Interfaces
如果一个组件实现了 ILayoutElement 接口，它就会被自动布局系统当做一个 layout element。
如果一个组件实现了 ILayoutGroup 接口，它被认为用来管理子节点的 RectTransforms。
如果一个组件实现了 ILayoutSelfController 接口，它被认为用来管理自己的 RectTransform。
**** Layout Calculations
自动布局系统安装下面的顺序来计算和执行布局：
1 通过调用 ILayoutElement 的 CalculateLayoutInputHorizontal 方法来计算 layout element 的 minimum,preferred,flexible widths。这是按照从下到上的顺序执行的，子节点会比他们的父节点先计算，这样父节点就可以在它的计算中获得它的子节点的信息。
2 layout element 的有效宽度会被计算，并且通过 ILayoutController 的 SetLayoutHorizontal 方法进行设置。这是按照从上到下的顺序进行的，子节点会比他们的父节点晚计算，因为子节点宽度的分配会基于父节点的整个宽度大小。这个步骤之后，layout elements 就会有他们新的宽度。
3 通过调用 ILayoutElement 的 CalculateLayoutInputVertical 方法来计算 layout element 的 minimum,preferred,flexible heights.这是按照从下到上的顺序执行的，子节点会比他们的父节点先计算，这样父节点就可以在它的计算中获得它的子节点的信息。
4 layout element 的有效高度会被计算，并且通过 ILayoutController 的 SetLayoutVertical 方法进行设置。这是按照从上到下的顺序进行的，子节点会比他们的父节点晚计算，因为子节点宽度的分配会基于父节点的整个高度大小。这个步骤之后，layout elements 就会有他们新的高度。
从上面可以看出，自动布局系统会先计算宽度，后计算高度，所以高度计算可以依赖宽度，但是宽度计算永远不能依赖高度。
**** Triggering Layout Rebuild
当组件的属性被修改引起当前的布局不可用时，需要对布局进行重新计算。可以通过下面的调用来触发布局的重新计算：
#+BEGIN_SRC c#
LayoutRebuilder.MarkLayoutForRebuild (transform as RectTransform);
#+END_SRC
这个重新构建不会立刻执行，而是在当前帧的最后，在渲染发生之前执行。不立即执行的原因是在一帧内可能会重建多次，如果每次都立即执行，会导致明显的性能下降。
通常需要在下面这些地方触发布局的重新计算:
在可以修改布局的属性设置函数中。
在下面这些回调函数中：
OnEnable
OnDisable
OnRectTransformDimensionsChange
OnValidate (only needed in the editor, not at runtime)
OnDidApplyAnimationProperties
* UI How Tos
** Designing UI for Multiple Resolutions
通过 Anchors 和 Canvas Scaler 来实现多分辨率适配。Anhors 可以处理 UI 元素的相对位置，CanvasScaler 用来处理 UI 元素的大小。
*** Canvas Scaler
CanvasScaler 组件用来控制 Canvas 上 UI 元素的像素密度和总体的缩放。这个缩放会影响到 Canvas 下的所有 UI 元素，包括字体的大小，和 Sprite 的边框。
UI Scale Mode 选项用来控制 UI 元素如何被缩放。
| ModeType               | 功能                                              |
|------------------------+---------------------------------------------------|
| Constant Pixel Size    | 	不考虑屏幕尺寸，UI 元素的尺寸保持和像素大小一样 |
| Scale With Screen Size | 	使 UI 元素在大的屏幕上变大                      |
| Constant Physical Size | 	不考虑屏幕尺寸和分辨率大小，UI 元素保持物理尺寸 |

Constant Pixel Size 缩放模式的参数：
| ArgName                   | 说明                                                                         |
|---------------------------+------------------------------------------------------------------------------|
| Scale Factor              | 	按照该缩放值缩放所有 Canvas 下的 UI 元素.                                      |
| Reference Pixels Per Unit | 	如果 Sprite 有 ‘Pixels Per Unit’ 设置,Sprite 中的一个像素就会占 UI 中的一个单位 |

Scale With Screen Size 缩放模式的参数：
| ArgName                   | 说明                                                                                    |
|---------------------------+-----------------------------------------------------------------------------------------|
| Reference Resolution      | UI 布局的设计分辨率.如果屏幕分辨率更大（更小），则 UI 将被放大（缩小）                  |
| Screen Match Mode         | 如果当前分辨率和 Reference 分辨率纵横比不一致，该参数用来指定缩放如何缩放 Canvas 的区域 |
| 1 Match Width or Height   | 以 width 或 height 或他们之间的值为依据缩放 canvas 区域                                 |
| 2 Expand                  | 在水平或竖直方向上扩展 canvas 区域，从而让 canvas 区域比 reference 区域大               |
| 3 Shrink                  | 在水平或竖直方向上裁剪 canvas 区域，从而让 canvas 区域比 reference 区域小               |
| Reference Pixels Per Unit | 如果一个 Sprite 有 ‘Pixels Per Unit’设置,Sprite 中的一个像素就会占用 UI 中的一个单位    |
当 ScreenMatchMode 选用 Match Width or Height 时，会有 Match 选项可供调节，它用来确定依据 width 还是 height 或者是他们之间的一个值来缩放 canvas 的区域。

Constant Physical Size 缩放模式的参数:
| ArgName                   | 说明                                                                                          |
|---------------------------+-----------------------------------------------------------------------------------------------|
| Physical Unit             | 	用来指定位置和尺寸使用的物理单位                                                            |
| Fallback Screen DPI       | 	如果屏幕的 DPI 不可知，则假定其 DPI 为该选项设置的值                                        |
| Default Sprite DPI        | 	有‘Pixels Per Unit’配置的 Sprites 使用的每英寸像素数目将匹配‘Reference Pixels Per Unit’配置 |
| Reference Pixels Per Unit | 	如果 Sprite 有‘Pixels Per Unit’设置, 则它的 DPI 将匹配‘Default Sprite DPI’设置              |

World Space Canvas 缩放模式的参数(当将 Canvas 的渲染模式设置为 WorldSpace 时会显示):
| ArgName                   | 说明                                                                                                                                                                |
|---------------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Dynamic Pixels Per Unit   | 在 UI 中动态创建 bitmaps 时（例如创建 Text），每个单位用到的像素数目。                                                                                              |
| Reference Pixels Per Unit | 如果 Sprite 有‘Pixels Per Unit’配置,Sprite 中的每个像素会占用世界中的一个单元。如果‘Reference Pixels Per Unit’被设置为 1,Sprite 的‘Pixels Per Unit’配置将按原样使用 |

Tips:
CanvasScaler 是通过修改 Canvas 的缩放值来实现缩放的。该缩放值可通过下面的方式获得：
需要注意的是，CanvasScaler 的 scaleFactor 属性和 Canvas 的 scaleFactor 并不是同一个值。CanvasScaler 的 scaleFactor 表示在 Constant Pixel Size 模式下 UI 元素的缩放值。而 Canvas 得 scaleFactor 表示无论什么模式下，当前 Canvas 的缩放值。
#+BEGIN_SRC c#
GetComponentInParent<Canvas> ().scaleFactor;
#+END_SRC
*** Screen And Reference Resolution
Screen.width 表示当前视图的像素宽度
Screen.height 表示当前视图的像素高度
Screen.resolutions 表示显示设备支持的所有全屏的分辨率
Screen.currentResolution 表示显示设备当前全屏的分辨率
#+BEGIN_EXAMPLE
// 下面打印出了 Screen.currentResolution 和 Screen.resolutions 的内容：
Screen.currentResolution = 1280 x 800 @ 0Hz
Screen.resolutions = 640 x 480 @ 0Hz
Screen.resolutions = 720 x 480 @ 0Hz
Screen.resolutions = 800 x 500 @ 0Hz
Screen.resolutions = 800 x 600 @ 0Hz
Screen.resolutions = 1024 x 640 @ 0Hz
Screen.resolutions = 1024 x 768 @ 0Hz
Screen.resolutions = 1152 x 720 @ 0Hz
Screen.resolutions = 1280 x 800 @ 0Hz
#+END_EXAMPLE
可以通过下面的方法来获取 ReferenceResolution
#+BEGIN_SRC c#
public static Vector2 GetCanvasReferenceResolution (GameObject gObj)
{
  CanvasScaler scaler = GUtility.GetComponentInSelfAndParent<CanvasScaler> (gObj);
  return scaler.referenceResolution;
}
#+END_SRC
* Scripts
** Scene
SceneManager.SceneManager.GetActiveScene().GetRootGameObjects()不会返回被标记为不被销毁的对象。

** Object
Object 中的几个静态方法。
| Name              | 功能                                                |
|-------------------+-----------------------------------------------------|
| Destroy           | 删除一个游戏对象或组件或资源.                       |
| DestroyImmediate  | 立即删除对象. 强烈建议使用 Destroy 代替此方法.        |
| DontDestroyOnLoad | 在加载一个新场景时，该对象不被自动销毁              |
| FindObjectOfType  | 返回第一个被加载的激活的 Type 类型的对象.             |
| FindObjectsOfType | 返回所有被加载的激活的 Type 类型的对象.              |
| Instantiate       | 克隆原始对象并返回克隆体.   |
Tips: 
DontDestroyOnLoad 只对场景中的 Root GameObjects 或他们上的组件有效。
创建一个空对象，然后对其调用 DontDestoryOnLoad 可以将该对象变为当前场景的 Root GameObject。
** GameObject
*** GameObject.Find(string childName) 静态成员方法
需要注意的是该方法会循环查找整个场景树的子节点。找到第一个名称为 childName 的节点。
该方法会返回标记为不被销毁的对象。
*** GameObject 定义的其他成员方法
| Name                    | 功能                                                                                |
|-------------------------+-------------------------------------------------------------------------------------|
| AddComponent	          | 添加一个类名称为 className 的组件到当前对象上.                                      |
| BroadcastMessage        | 调用当前对象以及其子对象上每个 MonoBehavior 上的名字单位 methodName 的方法          |
| CompareTag	            | 判断 gameObject 的 tag 与参数的 tag 相同 ?                                          |
| GetComponent            | 获取当前对象的指定类型的组件,不存在返回 null                                        |
| GetComponentInChildren  | 获取当前对象或其子对象的指定类型的组件，不存在返回 null（遍历行为是以深度为优先的） |
| GetComponentInParent	  | 获取当前对象或其父对象的指定类型的组件，不存在返回 null                             |
| GetComponents	         | 获取当前对象的所有组件                                                              |
| GetComponentsInChildren | 获取当前对象或其子对象的指定类型的所有组件。                                        |
| GetComponentsInParent	 | 获取当前对象或其父对象的指定类型的所有组件。                                        |
| SendMessage	           | 调用当前对象上每个 MonoBehavior 上的名字为 methodName 的方法                        |
| SendMessageUpwards      | 调用当前对象以及其父对象上每个 MonoBehavior 上的名字单位 methodName 的方法          |
| SetActive	             | 激活/不激活 当前对象                                                                |
**** Tips:
GetComponentInChildren(Type compType);
GetComponentsInChildren(Type compType);
GetComponentInParent(Type compType);
GetComponentsInParent(Type compType);
需要注意的是 
1 上面 4 个方法会先在当前对象中寻找 CompType 类型的组件。
2 方面 4 个方法会循环查找所有子节点或父节点
** Transform
*** transform.Find(string childName) 
Find 方法不是递归查找子节点的，它只查询直接子节点(不会查找自己)。
*** transform.root
该方法返回 transform 的 Root 节点。
*** 设置节点关系
SetAsFirstSibling	将 transform 放置到本地 transform 列表最前。
SetAsLastSibling	将 transform 放置到本地 transform 列表最后。
SetParent	将 transfrom 设置为当前 transform 的父节点.

** MonoBehavior
*** 各种函数函数触发时机
1 调用顺序如下
OnValidate -> OnValidate-> Awake -> OnEnable -> Start -> 
FixedUpdate -> Update-> LateUpdate -> 
(OnPreRender -> OnPostRender -> OnRenderImage)
-> OnDisable -> OnDestroy -> OnValidate
2 只有 Camera 下的脚本会触发 OnPreRender -> OnPostRender -> OnRenderImage
3 只有在编辑器模式下才会触发 OnValidate
#+BEGIN_SRC c#
public class MonoBehaviourTest : MonoBehaviour
{
	public static int counter = 1;

	// 脚本实例被加载时调用
	// Awake is called when the script instance is being loaded.
	public void Awake ()
	{
		GLogUtility.LogInfo (string.Format ("{0} Awake", counter++));
	}

	// 当脚本为 enabled，在任何 Update 方法第一次调用之前，会调用 Start
	// Start is called on the frame when a script is enabled just before any of
	// the Update methods is called the first time.
	public void Start ()
	{
		GLogUtility.LogInfo (string.Format ("{0} Start", counter++));
	}

	// 重置默认值，将脚本组件删除，再添加时会调用
	// Reset to default values.
	public void Reset ()
	{
		GLogUtility.LogInfo (string.Format ("{0} Reset", counter++));
	}

	// 当对象变为 enabled 或 active 时，调用 OnEnable
	//This function is called when the object becomes enabled and active.
	public void OnEnable ()
	{
		GLogUtility.LogInfo (string.Format ("{0} OnEnable", counter++));
	}

	// Monobehaviour 变为 Disabled 或 Inactive 时，会调用 OnDisable
	// This function is called when the behaviour becomes disabled () or inactive.
	public void OnDisable ()
	{
		GLogUtility.LogInfo (string.Format ("{0} OnDisable", counter++));
	}

	// MonoBehaviour 被销毁时会调用 OnDestroy
	// This function is called when the MonoBehaviour will be destroyed.
	public void OnDestroy ()
	{
		GLogUtility.LogInfo (string.Format ("{0} OnDestroy", counter++));
	}

	// 当脚本加载 或者 inspector 面板上的值被修改时会调用 OnValidate
	//This function is called when the script is loaded or a value is
	//changed in the inspector (Called in the editor only).
	public void OnValidate ()
	{
		GLogUtility.LogInfo (string.Format ("{0} OnValidate", counter++));
	}

	// OnPreRender is called before a camera starts rendering the scene.
	public void OnPreRender ()
	{
		GLogUtility.LogInfo (string.Format ("{0} OnPreRender", counter++));
	}
		
	// OnPostRender is called after a camera finished rendering the scene.
	public void OnPostRender ()
	{
		GLogUtility.LogInfo (string.Format ("{0} OnPostRender", counter++));
	}

	// OnRenderImage is called after all rendering is complete to render image.
	public void OnRenderImage (RenderTexture src, RenderTexture dest)
	{
		GLogUtility.LogInfo (string.Format ("{0} OnRenderImage", counter++));
	}

	// 如果物体是可见的，每个摄像机触发一次 OnWillRenderObject 的调用
	// OnWillRenderObject is called once for each camera if the object is visible.
	public void OnWillRenderObject ()
	{
		GLogUtility.LogInfo (string.Format ("{0} OnWillRenderObject", counter++));
	}

	// 当前的 collider/rigidbody 和另外的 collider/rigidbody 开始接触时，会调用 OnCollisionEnter
	// OnCollisionEnter is called when this collider/rigidbody has begun touching another
	// rigidbody/collider.
	public void OnCollisionEnter ()
	{
		GLogUtility.LogInfo (string.Format ("{0} OnCollisionEnter", counter++));
	}

	// 当前的 collider/rigidbody 和另外的 collider/rigidbody 停止接触时，会调用 OnCollisionExit
	// OnCollisionExit is called when this collider/rigidbody has stopped touching another
	// rigidbody/collider.
	public void OnCollisionExit	()
	{
		GLogUtility.LogInfo (string.Format ("{0} OnCollisionExit", counter++));
	}

	// 每一个和其他 collider/rigidbody 有接触的 collider/rigidbody 都会在每帧中触发 OnCollisionStay 的调用
	// OnCollisionStay is called once per frame for every collider/rigidbody that is touching
	// rigidbody/collider.
	public void OnCollisionStay ()
	{
		GLogUtility.LogInfo (string.Format ("{0} OnCollisionStay", counter++));
	}

	public void OnTriggerEnter ()
	{
		GLogUtility.LogInfo (string.Format ("{0} OnTriggerEnter", counter++));
	}

	public void OnTriggerExit ()
	{
		GLogUtility.LogInfo (string.Format ("{0} OnTriggerExit", counter++));
	}

	public void OnTriggerStay ()
	{
		GLogUtility.LogInfo (string.Format ("{0} OnTriggerStay", counter++));
	}

	// 如果 MonoBehaviour 状态为 enabled，则以固定的帧率调用此函数
	//This function is called every fixed framerate frame, if the MonoBehaviour is enabled.
	public void FixedUpdate ()
	{
		GLogUtility.LogInfo (string.Format ("{0} FixedUpdate", counter++));
	}

	// 如果 MonoBehaviour 状态为 enabled，则以固定的帧率调用此函数
	// Update is called every frame, if the MonoBehaviour is enabled.
	public void Update ()
	{
		GLogUtility.LogInfo (string.Format ("{0} Update", counter++));
	}

	// 如果 MonoBehaviour 状态为 enabled，则以每帧都会调用此函数
	// LateUpdate is called every frame, if the Behaviour is enabled.
	public void LateUpdate ()
	{
		GLogUtility.LogInfo (string.Format ("{0} LateUpdate", counter++));
	}
}
#+END_SRC
*** 单例 MonoBehavior
单例 MonoBehavior 被添加到多个 GameObject 上后，对于每个 GameObject，都分别实例化了一个 MonoBehavior 对象，这些对象和你自己实例化的单例不是同一个对象。
DocUpdate:
创建 MonoBehavior 单例是不被允许的，会提示下面错误:
#+BEGIN_EXAMPLE
You are trying to create a MonoBehaviour using the 'new' keyword.  This is not allowed.  MonoBehaviours can only be added using AddComponent().  Alternatively, your script can inherit from ScriptableObject or no base class at all
#+END_EXAMPLE
*** public 变量赋值顺序
public 变量的赋值顺序按照 初始化语句、构造函数、编辑器赋值的顺序。
#+BEGIN_SRC c#
public class Test:MonoBehaviour
{
	public int value2 = 10;

	public Test ()
	{
		Debug.Log ("Test value2 = " + value2.ToString ());

		value2 = 11;
	}

	void Awake ()
	{
		Debug.Log ("Awake value2 = " + value2.ToString ());
	}

	void Start ()
	{
		Debug.Log ("Start value2 = " + value2.ToString ());
	}
}
// Output
Test value2 = 10    //构造函数中读的值为 初始化语句中赋的值
Awake value2 = 120  //在编辑器中设置了 value2 的值为 120, 所以编辑器赋值在 Awake 之前执行的。
Start value2 = 120
#+END_SRC
** Resource
*** Load
需要注意一下两点
1 使用 Resource.Load 时，其中参数不能填写后缀名，否则返回 null.
2 通过 Resource.Load 返回的是 Prefab 本身，需要对其实例化才能使用。否则会报下面的错误
Setting the parent of a transform which resides in a prefab is disabled to prevent data corruption.
#+BEGIN_SRC c#
var obj = Resources.Load ("UI/Root_bg") as GameObject;
obj.transform.SetParent(rootUI);
#+END_SRC
** Animator
animator 中的条件
** Attributes
*** RuntimeInitializeOnLoadMethod
设置了[RuntimeInitializeOnLoadMethod]属性的静态函数，在场景加载完成后会被调用(Awake 消息触发之后调用)。
不同文件中的[RuntimeInitializeOnLoadMethod]属性的静态函数调用顺序是不确定的。
* Optimize
** Optimizing Graphics Performance
#+BEGIN_EXAMPLE
翻译自 OptimizingGraphicsPerformance.html
#+END_EXAMPLE
好的性能是很多游戏成功的关键。下面是一些最大化游戏图形渲染速度的简单指导方针。
*** where are the graphics costs
哪些地方会有图形消耗?
游戏的图形部分主要会消耗计算机的两大系统：GPU 和 CPU。任何优化的第一准则就是找出性能问题发生在哪儿。因为优化 GPU 和 CPU 的策略会非常不同（甚至是相反的，通常会让 GPU 一次做更多的工作来实现优化，而 CPU 则恰恰相反）

**** 典型的瓶颈以及检测他们的方法
***** GPU 通常会受到填充率和内存带宽的限制:
是否游戏在低分辨率设备上运行的更快？如果是这样，你很可能是受到了填充率在 GPU 上的限制。
***** CPU 通常会受到需要被渲染的批处理的数量的限制
在 Rendering Statistics 窗口可以检查”batches”的数量。

当然，这里只有首要的原则；瓶颈也可能发生在其他什么地方。比较不典型的瓶颈有：
***** 不是渲染的问题，无论是在 GPU 还是 CPU 上。
例如你的脚本和物理可能才是真正的问题。用 Profiler 可以将其指出来。
***** GPU 有很多顶点需要处理。多少个顶点是可以接受的，这一点取决于 GPU 以及顶点着色器的复杂度。
通常数据表明，在移动设备上，顶点数目不要超过 10 万个，在 PC 平台上，不要超过几百万个。
***** 对于一些需要在 CPU 进行的顶点处理，CPU 也有很多顶点需要处理。
例如，网格蒙皮，布料模拟，特效等。

*** CPU optimization
为了渲染屏幕上的任何物体，CPU 必须要做一些工作——计算出哪些光照影响到了这些物体，设置着色器以及他们的参数，发生绘制命令给图形驱动，图形驱动会准备这些命令发送给图形卡（显卡）。所有这些每个物体的 CPU 消耗都不廉价，有很多可见的物体时，消耗会叠加。
所以，如果你有一千个三角形，他们如果都在一个网格内，那将会比每个三角形都有一个独立的网格的情况要高效很多。这两种情况在 GPU 上的消耗是差不多的，但是在 CPU 上，渲染一千个物体和一个物体所做的工作将有很明显差别。

为了让 CPU 少做一些工作，最好减少可见物体的数量：
***** 使用手动方式或者 Unity 的 draw call 批处理方式，将靠近的物体组合在一起。
***** 游戏物体使用尽可能少的材质，将不同的贴图放到一张更大的贴图地图中。
***** 尽可能少使用导致多次渲染物体的效果（例如，反射、阴影、基于像素的光照等等）

组合物体到一起从而每个网格最少有几百个三角形并且为整个网格使用一个材质。将两个不共享同一材质的物体合并在一起不会获得任何性能的提升。最常见的需要有多个材质的原因是两个网格使用不同的贴图，所以，为了优化 CPU 性能，你应该保证你组合到一起的物体使用同一个贴图。

然而，在正向渲染中，当使用很多基于像素的光照，有很多情况下，将多个物体合并可能不会管用，就像下面的解释。
*** GPU: Optimizing Model Geometry
优化一个模型的几何时，有两个基础的准则：
***** 不要使用任何多余的不必要的三角形
***** 保持 UV 贴图接缝和硬边缘的数目越少越好
需要注意的是图形硬件需要处理的实际的顶点的数目通常和 3D 应用程序导出的顶点的数目是不相同的。模型应用程序通常显示的是几何顶点数目，例如组成模型的不同的角点。然而，对于显卡来说，为了渲染的目的，一些结合顶点需要被分为两个或更多个逻辑顶点。如果一个顶点有多个法线、贴图坐标或顶点颜色，这个顶点就必须被分为多个逻辑顶点。因此，Unity 中的顶点数目总是要比 3D 应用程序所给的顶点数目多。

尽管模型中的几何数量大多会影响到 GPU，在 Unity 中一些特性依然会在 CPU 中处理模型，例如网格蒙皮。
*** Lighting Performance
不进行计算的光照总是最快的！只需要使用光照贴图来 bake 静态光照一次，就可以代替每一帧的光照计算。在 Unity 中，生成光照贴图环境的处理过程所花的时间只会比将一个光照放在场景中长一点，但是：
***** 光照贴图要运行的更快（比基于像素的光照快 2-3 倍）
***** 并且看上去效果要更好，因为你可以烘焙的全局照明而且光照贴图可以平滑化结果。
在很多情况下，在 shader 和内容中有一些简单的技巧可以代替到处添加光照。例如，可以在 shader 中添加专门的边缘发光计算，来代替添加一个光照直接照射摄像机从而获得边缘发光的效果。
**** Lights in forward rendering
基于像素的动态光照会给每个被影响的像素增加明显的渲染负荷，并且会导致物体在多个阶段中被渲染。在性能低的设备上，例如移动设备或底端 PC GPU 上，需要避免有多于一个的像素光照照明任何一个物体，并且使用光照贴图代替每帧的光照计算来照亮静态物体。基于顶点的动态光照会给顶点变换添加明显的消耗。尽可能避免多个光照照明任何一个给定物体的情况。
如果你使用基于像素的光照，每个网格必须被渲染的次数和它被照明的像素光照的数目是相同的。如果你合并两个相距较远的物体，这将会增加组合物体的有效尺寸。所有的照明了组合物体的任何一部分的像素光照，在渲染过程中都会被考虑，所以需要执行的渲染阶段的数量将会增加。通常渲染组合物体时，需要执行的阶段数目是所有分开的物体的阶段数目的总和，所以组合没有获得任何好处。基于这样的原因，你不应该将分开的比较远的不被同一组像素光照影响的网格合并在一起。

在渲染期间，Unity 会找出一个网格周围的所有光照，并且计算其中有哪些光照对物体影响最大。Quality Settings 用来修改有多少光照最终被当做像素光照，以及有多少被当做顶点光照。每个光照会基于它离网格的距离以及它的照明强度来计算它的重要性。更进一步，只从游戏内容来看，一些光照比另外一些要更重要。基于这样的原因，每个光照都有一个 RenderMode 设置，它可以被设置为 Important 或者 Not Important；被标记为 Not Important 的光照通常会有较低的渲染负载。
例如，在一个驾驶游戏中，玩家在黑暗中打开车头灯驾驶。车头灯很可能是游戏中最明显的光源，所以他们的 RenderMode 应该被设置为 Important。另一方面，游戏中一定包含不太重要的等（汽车的尾灯）并且使用像素光照，他们也不会改善可视化效果。这样的灯光应该被设置为 Not Important，从而避免在只能获得很小效果的地方浪费渲染能力。

优化基于像素的光照可以同时节省 CPU 和 GPU 消耗：对于额外的物体渲染，CPU 有更少的 draw call 需要做，GPU 有更少的顶点需要处理、更少的像素需要光栅化。
*** GPU: Texture Compression and Mipmaps
使用压缩贴图将会减低你的贴图大小（从而使加载时间更快，内存占用更小）并且可以显著地增加渲染性能。压缩的贴图所使用的内存带宽和未压缩的 32 位 RGBA 贴图所使用的内存带宽相比，只是一小部分。
**** Use Texture Mip Maps
首要的规则是，对于在 3D 场景中使用的贴图，应该总是开启 MipMaps 生成。在 GPU 渲染时，就像贴图压缩可以帮助限制贴图数据的数量，一个 mip mapped 贴图可以让 GPU 为更小的三角形使用低分辨率的贴图。
这个规则的唯一的例外是贴图图元以 1 比 1 映射到屏幕像素，例如 UI 元素，或者是在 2D 游戏中。

*** LOD and Per-Layer Cull Distances
在一些游戏中，为了减低 CPU 和 GPU 的负载，积极地剔除比较小的物体可能更合适。例如，小石块和碎片应该在距离很远时变的不可见，然而巨大的建筑却依然可见。
这可以通过 Level Of Detail system 来实现，或者通过在摄像机上手动设置每个层的剔除距离。你可以将小物体放到一个分开的层中并且使用 Camera.layerCullDistances 脚本函数来设置每个层的剔除距离。

*** Realtime Shadows
实时阴影非常的棒，但他们会消耗很多的性能，在 CPU 上会有额外的 draw calls，在 GPU 上也有额外的处理。
更多详细情况，请参阅 Light Performance。

*** GPU: Tips for writing high-performance shaders
毫不夸张地讲，一个高端的 PC GPU 和一个底端的移动设备 GPU 有几百倍的性能差别。即使在同一平台上，也是一样的。在一个 PC 上，一个快速的 GPU 要比一个慢速的集成的 GPU 快几十倍；在移动平台上你也可以看到 GPU 直接的巨大差异。
所以需要记住移动平台和底端 PC 上的 GPU 性能会比你的开发机器低很多。通常着色器需要手动优化来减低计算和贴图读取，从而获得好的性能。例如，内置的 Unity 着色器有他们等价的“mobile”版本，他们会更加高效（但是有一些限制或者近似 - 这使得他们更高效）。

下面是一些指导方针，他们对于移动平台和底端 PC 显卡比较重要：
**** Complex mathematical operations
超越数学函数（幂函数、指数函数，对数函数，余弦函数，正弦函数，正切函数等）是非常昂贵的，所以一个好的首要规则是每个像素不要超过一个这样的操作。在适用的地方，可以考虑将贴图查询作为可选方案。
尝试编写你自己的规范化、点积、inverse sqrt 操作是不明智的。如果你适用内置的方法，驱动会为你生成更好的代码。
记住 alpha 测试（discard）操作将会是你的片段处理变慢。
**** Floating point operations
在写自定义的着色器时，你应该总是指定浮点数变量的精度。选择尽可能小的浮点数格式来获得最好的性能是至关重要的。操作的精度在很多桌面 GPU 上是完全被忽略的，但是对于很多移动平台的 GPU 却是至关重要的。
如果 shader 是使用 Cg/HLSL 编写的，可以按照下面描述来指定精度：
float - 32 位浮点数格式，适用于顶点变换但它是性能最慢的.
half  - 16 位浮点数格式，适用于贴图 UV 坐标并且比 float 差不多要快 2 倍.
fixed - 10 位浮点数格式，适用于颜色，光照计算和其他高性能操作并且比 float 差不多快 4 倍.
如果 shader 是用 GLSL 编写的，浮点数精度是分别通过 highp、mediump、lowp 来指定的。
关于 shader 性能的更多的详细信息可以在 Shader Performance 页面中找到。

*** Simple Checklist to make Your Game Faster
**** 在 PC 平台下，依据目标 GPU 不同，保持每帧的顶点数目低于 200k 到 3M
**** 如果你使用内置着色器，请选择移动平台类型或无光照类型。他们可以在非移动平台上也可以很好的运行；他们只是更复杂的着色器的简化版和近似版。
**** 保持每个场景中不同材质的数目比较少，尽量在多个不同的物体之间共享材质。
**** 为不移动的物体设置静态属性，从而允许静态批处理等内部优化。
**** 不要使用不必要的像素光照，应该选择只有一个像素光照可以影响你的几何体。
**** 不要使用不必要的动态光照，应该选择烘焙光照来代替。
**** 如果可以的话尽量使用压缩格式的贴图，另外和 32 位贴图相比优先选择 16 位贴图格式。
**** 不要使用不必要的雾效果。
**** 了解遮挡剔除的好处，在有很多遮挡的静态场景的情况下，使用它来减低可见几何体和 draw calls 的数量.规划你的场景从遮挡剔除中获益。
**** 使用天空盒来伪造远处的几何体。
**** 使用像素着色器或贴图组合器来混合多个贴图从而代替多个阶段的处理。
**** 如果编写自定的着色器，应该总是尽可能使用最小的浮点数格式：
fixed / lowp    - 用于颜色，光照信息和法线
half  / mediump - 用于 UV 坐标
float / highp   - 避免在像素着色器中使用，最好用于在顶点着色器中计算位置。
**** 在像素着色器中，最小化使用复杂的数学运算，例如 pow sin cos 等等。
**** 对于每个片段，尽可能使用少的贴图。
** Draw Call Batching
#+BEGIN_EXAMPLE
翻译自 DrawCallBatching.html
#+END_EXAMPLE
为了将一个物体绘制在屏幕上，引擎必须发送一个绘制调用给图形 API（例如,OpenGL 或 Direct3D）。绘制调用通常是很昂贵的，每一次绘制调用都会有图形 API 做一些重要的工作，导致在 CPU 端有性能负载。这大多数是因为不同的绘制调用之间状态的改变而引起的（例如，切换不同的材质），这导致了图形驱动中，昂贵的生效和变换步骤。
Unity 使用 static batching 来处理这种情况。静态批处理的目标是将尽可能多的网格重新分组到尽可能少的 buffer 中，从而获得更好的性能。这样做的结果是少量的巨大的网格会被渲染，从而代替了大量的低效的小的网格。Unity 会在同样的资源上循环渲染这些资源的不同区间。它为每个 static batched 网格，高效地执行一系列的快速绘制调用。
Unity 中内置的批处理支持比简单地合并几何体到模型中要有很显著的好处。在 Unity5.0 中，开始时只有一个构建的索引缓存区，然后对于大网格的每一个可见的子网格，会提交一个绘制调用。
*** Materials
只有共享相同材质的物体才可以被 batch 在一起。所以，如果你想好的 batching，你需要尽可能在多个不同物体之间共享材质。
如果你有两个不同的材质他们只是贴图不同，你可以将这些贴图合并到一个大贴图中（这个处理过程经常被称做贴图地图）。当贴图在同一个贴图地图中时，你就可以用一个材质来代替多个不同材质了。
如果你需要在脚本中访问共享的材质属性，非常重要的一点是修改 Renderer.material 将会创建一个材质副本。而你应该使用 Renderer.sharedMaterial 来保持材质的共享。
*** Dynamic Batching
Unity 可以自动 batch 移动的物体到相同的 draw call 中，条件是他们需要共享相同的材质以及满足一些其他条件。Dynamic batching 是自动进行的并且不需要你的任何额外工作。
**** Tips:
***** 批处理动态物体对于每个顶点都有负荷，所以只会应用于顶点属性总数少于 900 的网格。
****** 如果你的着色器使用顶点位置、法线和一个 UV、你可以批处理 300 个顶点；然而，如果你需要使用顶点位置、法线、UV0、UV1 以及切线，你只可以批处理 180 个顶点。
****** 请注意：属性数量限制在未来可能会改变。Please note: attribute count limit might be changed in future
***** 一般来讲，物体应该使用相同的缩放比例。
非统一缩放对象属于例外；如果很多对象都有不同的非统一缩放，它们依然可以被 batched。
***** 使用不同的材质实例（即使他们相同）将使得物体无法被一起 batched。
***** 使用光照贴图的物体有额外的渲染参数：光照贴图索引以及光照贴图中的偏移和缩放。所以通常来讲动态光照贴图对象应该指定相同的光照贴图位置来支持 batched。
***** 多阶段着色器将会打破批处理。在正向渲染中，几乎所有的 unity 着色器都支持多个光照，实际上是为他们执行额外的阶段。额外的像素光照的绘制调用将不会被 batched。
***** 接收实时阴影的物体也不可以被 batched。
*** Static Batching
另一方面，静态批处理允许引擎降低任意大小几何体的 draw calls（假如它不会移动并且共享相同的材质）。静态批处理比动态批处理效果更加显著，但是它会使用更多的内存。你应该选择使用静态批处理，因为它只占用少量的 CPU 功能。

为了利用静态批处理的优势，你需要显式地指定特定的物体在游戏中是静止的，将不会被移动，旋转和缩放。在 Inspector 面板中勾选 Static 选项即可。

使用静态批处理将需要额外的内存来存储组合后的几何体。在静态批处理之前，如果多个物体共享同一个几何体，这是会为每个对象创建一个几何体副本，无论是在编辑器中还是在实际运行中。这可能并不是一个好的主意 - 有时候你必须为一些物体避免使用静态批处理牺牲渲染性能来保持较低的内存占用。例如，在一个稠密的森林关卡中，将树木标记为静态会有很严重的内存影响。

在内部实现中，静态批处理将静态物体转换到世界空间，并且建立一个顶点和索引缓冲区。然后，在同一个批处理中的所有可见物体，会执行一系列的廉价的 draw calls，这些 draws 之间几乎没有状态改变。所以，技术上来讲静态批处理并没有节省“3D API draw calls”，但是它节省了不同 draw calls 之间的状态改变（这是非常耗时的一部分）。
*** Other batching tips
目前，只有 Mesh Renderers 和 Particle Systems 是被 batched 的。这意味着网格蒙皮、布料、路径渲染以及其他类型的渲染组件是不被 batched。

半透明着色器通常需要以从后到前的顺序渲染物体。Unity 首先会以这样的顺序排列物体，然后尝试将他们批处理（但是，因为必须满足严格的顺序，这就意味着比起不透明物体来讲，只有更少的物体可以批处理）。

为了批处理 draw call，手动组合那些互相比较靠近的物体可能是一个比较好的选择。例如，一个放有很多衣物的静态橱柜被组合为一个网格是有意义的，你可以通过 3D 模型应用程序或者是使用 Mesh.CombineMeshes 来实现组合。
** Modeling characters for optimal performance
#+BEGIN_EXAMPLE
翻译自 ModelingOptimizedCharacters.html
#+END_EXAMPLE
Below are some tips for designing character models to give optimal rendering speed.
下面是设计角色模型达到最佳渲染速度的一些提示：
*** 使用单个蒙皮网格渲染 
你应该为每个角色只使用一个蒙皮网格渲染。Unity 使用可见性剔除和边界体积更新来优化动画，并且这些优化在只使用了一个 Animation 组件以及一个 Skinned Mesh Renderer 组件的时候才激活。使用两个 Shinned Mesh Renderer 来代替单个 Shinned Mesh Renderer 会导致一个模型的渲染时间几乎翻倍，使用多个网格很少有任何实际优势。
*** 使用尽可能少的材质
你应该尽可能降低每个网格使用的材质数目。为一个角色使用多个材质的唯一原因是你需要为角色的不同部位使用不同的着色器。然而，在大多数情况下，每个角色使用 2-3 个材质应该是足够了。
*** 使用尽可能少的骨骼
在一个典型的桌面游戏中，一个骨骼层级中大概会使用 15-60 个骨骼。使用的骨骼数目越少，性能会越好。使用 30 个骨骼的话，你可以在桌面平台和移动平台上都获得不错的品质。理性情况下，保证移动平台中骨骼数目少于 30 个，并且在桌面游戏中不要超出 30 个太多。
*** 多边形数目
多边形的数目取决于你需要的品质以及你的目标平台。对于移动设备来说，每个网格的多边形介于 300 和 1500 个会有一个好的结果，然而，对于桌面平台来说，理想的范围是 1500 到 4000。在任何给定时间点，如果游戏中有很多角色出现在屏幕上，你可能需要降低每个网格的多边形的数量。
*** 保持正向运动和反向运动分开
当动画被导入时，一个模型的反向运动节点会被烘焙到正向运动中作为最终结果，Unity 不需要反向运动节点。然而，如果将他们留在模型中他们会有 CPU 负载，尽管他们不影响动画。你可以依据你的偏好在 Unity 中或者是使用模型工具删除这些冗余的逆向运动节点。理想的情况是，你应该在建模的过程中，保持反向运动和正向运动层级分开，从而在需要删除反向运动节点时会比较容易。
** Optimizing Shader Load Time
#+BEGIN_EXAMPLE
翻译自 OptimizingShaderLoadTime.html
#+END_EXAMPLE
着色器都是在 GPU 上执行的小程序，加载它们会花费一些时间。通常情况下每个独立的 GPU 程序不会花费太多的加载时间，但是在内部着色器会有很多变体。
例如，标准着色器，如果完全编译的话，最终会是成千上万个稍微不同的 GPU 程序。这造成了两个潜在的问题：
**** 巨大数量的着色器变体增加了游戏编译时间，以及游戏的大小。
**** 在游戏中，加载巨大数量的着色器变体会比较慢，并且占用会内存。
*** Shader build time stripping
着色器编译时间剥离

在编译游戏时，Unity 可以检测一些内部的着色器变体不会被游戏用到，并且可以忽略他们。下面两种情况下，会剥离着色器编译时间：
**** 独立的着色器特性，对于使用了#pragma shader_feature 的着色器。如果在使用的材质中，没有用到这个特定的变体，该着色器变体不会被包含在编译中。详细信息可以查看 internal shader variants 文档。除了内置着色器以外，标准着色器也是这样的。
**** 着色器变体用来处理雾并且光照贴图模式没有被任何场景使用时，着色器变体也不会被包含在游戏数据中。如果你想覆盖这种行为，你可以查看 Graphics Settings 文档。

组合上面的基本上可以降低着色器数据的大小。例如，一个完全编译的标准着色器将会占用几百兆字节，但是一个特定的项目中最终只会占用两兆字节（并且在应用程序打包处理时会进一步压缩）。
*** Default Unity shader loading behavior
在所有默认设置情况下，Unity 加载 shaderlab 着色器对象到内存中，但并不会创建内置的着色器变体，直到他们被需要的时候。
这就意味着被包含在游戏编译中的着色器变体还是有可能被使用，但是并不会有内存占用也没有加载时间消耗，直到他们被需要的时候。例如，着色器总是包含一个变体来处理带有阴影的点光照，但是，如果你最终没有在游戏中使用带有阴影的点光源，就不会加载这个特定的变体。
然而，默认行为的一个缺点是，当第一次需要某个特定的着色器变体时，可能会造成卡顿，因为一个新的 GPU 程序被加载到图形驱动中。在游戏过程中，这通常是不希望看到这种情况的，所以 Unity 有 ShaderVariantCollection 资源来帮助解决这个问题。

*** Shader Variant Collections
ShaderVariantCollection 是一个基于着色器列表的资源，对于列表中的每个元素，有一个 Pass 类型列表和 shader 关键字组合被加载。
为了基于实际使用的着色器和他们的变体来创建这些资源，编辑器可以追踪哪些着色器以及他们的变体在实际中被使用。在 Graphics Settings 中，有一个按钮可以依据当前追踪的着色器来创建一个新的 ShaderVariantCollection，或者是清除当前追踪的着色器列表。
一旦你有了 ShaderVariantCollection 资源，你可以设置着色器变体在游戏加载时自动加载(在 Graphics Settings 下的 Preloaded Shaders 列表中设置)，或者你可以预加载独立的着色器变体集合。详细信息可以查看 ShaderVariantCollection 脚本类。
* Error
** Setting the parent of a transform which resides in a prefab is disabled to prevent data corruption.
错误的原因是，prefab 加载后不能直接加入到场景中。必须要以 prefab 为父本生成克隆对象，将克隆对象作为操作的对象加入场景。
#+BEGIN_SRC c#
public static GameObject CreateView ()
{
	// 正确的方式
  return GameObject.Instantiate (Resources.Load ("UI/Root_start") as GameObject);
}
public static GameObject CreateView ()
{
	// 错误的方式
  return Resources.Load ("UI/Root_start") as GameObject;
}
#+END_SRC
* Q&A
** 为什么基于像素的光照会导致物体的多次渲染？

